import json
import os
import subprocess
import sys
from pathlib import Path

SCALAR_TYPES = {"string", "int", "int64", "float64", "bool"}

def is_scalar_pointer_type(go_type: str) -> bool:
    return go_type in {"*string", "*int", "*int64", "*float64", "*bool"}

def is_scalar_type(go_type: str) -> bool:
    return go_type in SCALAR_TYPES

def resolve_field_type(field: dict) -> str:
    proposed = field.get("proposed_go_type", "any")
    required = field.get("required", False)
    nullable = field.get("nullable", False)
    has_default = field.get("has_default", False)
    presence_note = field.get("decode_presence_note", "")

    if proposed.startswith("*"):
        return proposed

    if nullable and is_scalar_type(proposed):
        return f"*{proposed}"

    if not required and not nullable and is_scalar_type(proposed):
        if has_default or presence_note:
            return f"*{proposed}"

    return proposed

def default_to_go_literal(go_type: str, default_value: str) -> str:
    if go_type == "*string" or go_type == "string":
        return json.dumps(default_value)
    if go_type == "*bool" or go_type == "bool":
        return "true" if str(default_value).lower() == "true" else "false"
    if go_type == "*int" or go_type == "int":
        return str(int(default_value))
    if go_type == "*int64" or go_type == "int64":
        return f"int64({int(default_value)})"
    if go_type == "*float64" or go_type == "float64":
        return str(float(default_value))
    return json.dumps(default_value)

def find_gofmt() -> str:
    for candidate in [
        r"C:\Program Files\Go\bin\gofmt.exe",
        r"C:\Program Files (x86)\Go\bin\gofmt.exe",
    ]:
        if os.path.isfile(candidate):
            return candidate
    return "gofmt"

def generate_go_dto(plan_path: str, out_path: str):
    with open(plan_path, "r", encoding="utf-8") as fh:
        plan = json.load(fh)

    schemas = plan.get("schemas", [])
    lines = []
    lines.append("// Code generated by tools/generate_go_dtos.py. DO NOT EDIT.")
    lines.append("")
    lines.append("package dto")
    lines.append("")

    imports = set()
    imports.add("encoding/json")

    for schema in schemas:
        for field in schema.get("fields", []):
            pt = field.get("proposed_go_type", "")
            if "json.RawMessage" in pt:
                imports.add("encoding/json")

    if imports:
        lines.append("import (")
        for imp in sorted(imports):
            lines.append(f'\t"{imp}"')
        lines.append(")")
        lines.append("")

    for schema in schemas:
        schema_name = schema["schema_name"]
        fields = schema.get("fields", [])
        lines.append(f"// {schema_name} generated from OpenAPI schema.")
        lines.append(f"type {schema_name} struct {{")

        has_defaults = False
        defaultable_fields = []

        for field in fields:
            go_field_name = field.get("go_field_name", field["name"])
            json_tag = field.get("json_tag", field["name"])
            resolved_type = resolve_field_type(field)
            blockers = field.get("blockers", {})
            presence_note = field.get("decode_presence_note", "")
            default_app_note = field.get("default_application_note", "")
            has_default = field.get("has_default", False)

            if has_default:
                has_defaults = True
                defaultable_fields.append(field)

            comments = []
            if blockers:
                if isinstance(blockers, dict):
                    for k, v in blockers.items():
                        comments.append(f"// BLOCKER [{k}]: {v}")
                elif isinstance(blockers, list):
                    for item in blockers:
                        comments.append(f"// BLOCKER: {item}")
            if presence_note:
                comments.append(f"// PRESENCE: {presence_note}")
            if default_app_note:
                comments.append(f"// DEFAULT: {default_app_note}")

            for c in comments:
                lines.append(f"\t{c}")
            lines.append(f"\t{go_field_name} {resolved_type} `json:\"{json_tag}\"`")

        lines.append("}")
        lines.append("")

        if has_defaults:
            lines.append(f"// ApplyDefaults applies default values for optional pointer scalar fields in {schema_name}.")
            lines.append(f"func (dto *{schema_name}) ApplyDefaults() {{")
            for field in defaultable_fields:
                go_field_name = field.get("go_field_name", field["name"])
                resolved_type = resolve_field_type(field)
                default_value = field.get("default_value", "")
                if is_scalar_pointer_type(resolved_type):
                    lit = default_to_go_literal(resolved_type, default_value)
                    lines.append(f"\tif dto.{go_field_name} == nil {{")
                    lines.append(f"\t\tv := {lit}")
                    lines.append(f"\t\tdto.{go_field_name} = &v")
                    lines.append(f"\t}}")
                else:
                    lines.append(f"\t// TODO: non-scalar default application for {go_field_name} ({resolved_type})")
            lines.append("}")
            lines.append("")

    out_dir = os.path.dirname(out_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    with open(out_path, "w", encoding="utf-8", newline="") as fh:
        fh.write("\n".join(lines) + "\n")

    gofmt = find_gofmt()
    try:
        subprocess.run([gofmt, "-w", out_path], check=True)
    except Exception as e:
        print(f"Warning: gofmt failed: {e}")

    print(f"Generated {len(schemas)} schemas to {out_path}")

if __name__ == "__main__":
    base = Path(__file__).resolve().parent.parent
    plan = base / "contracts" / "go-dto-mapping-plan.json"
    out = base / "go-service" / "internal" / "dto" / "types_gen.go"
    generate_go_dto(str(plan), str(out))

